import { ArchNodeType, type ArchNodeData, type ArchEdgeData, type Architecture, type ArchNode, type ArchEdge } from '@system-vis/shared';

export function getSampleArchitecture(): Architecture {
  // Sample e-commerce/social media platform architecture
  const nodes: ArchNode[] = [
    {
      id: 'node_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'Web Frontend',
        nodeType: ArchNodeType.FRONTEND,
        instances: 2,
        cpuPerInstance: 2,
        memoryPerInstanceMB: 1024,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 5000,
        baseLatencyMs: 50,
        latencyStdDevMs: 10,
        failureRate: 0.001,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_api_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 150 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 10000,
        authEnabled: true,
        corsEnabled: true,
        maxRPS: 10000,
        baseLatencyMs: 20,
        latencyStdDevMs: 5,
        failureRate: 0.0005,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_load_balancer',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 300 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'least_connections',
        healthCheckIntervalMs: 10000,
        maxRPS: 8000,
        baseLatencyMs: 10,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_service_api',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 50, y: 450 },
      data: {
        label: 'User Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 3,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 75,
        maxRPS: 3000,
        baseLatencyMs: 100,
        latencyStdDevMs: 20,
        failureRate: 0.002,
        maxConcurrentRequests: 15000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_service_order',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 250, y: 450 },
      data: {
        label: 'Order Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 4,
        cpuPerInstance: 6,
        memoryPerInstanceMB: 3072,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 4000,
        baseLatencyMs: 150,
        latencyStdDevMs: 30,
        failureRate: 0.003,
        maxConcurrentRequests: 20000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_service_payment',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 450, y: 450 },
      data: {
        label: 'Payment Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 2,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 2000,
        baseLatencyMs: 200,
        latencyStdDevMs: 50,
        failureRate: 0.001,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 650, y: 450 },
      data: {
        label: 'Message Queue',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 100000,
        consumerCount: 5,
        consumerProcessingMs: 500,
        partitions: 10,
        maxRPS: 5000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_cache',
      type: ArchNodeType.CACHE,
      position: { x: 200, y: 600 },
      data: {
        label: 'Redis Cache',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 4096,
        hitRate: 0.85,
        ttlSeconds: 3600,
        evictionPolicy: 'lru',
        maxRPS: 50000,
        baseLatencyMs: 3,
        latencyStdDevMs: 1,
        failureRate: 0.00001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_database',
      type: ArchNodeType.DATABASE,
      position: { x: 400, y: 600 },
      data: {
        label: 'PostgreSQL DB',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 500,
        readReplicas: 2,
        avgQueryLatencyMs: 100,
        connectionPoolSize: 100,
        maxRPS: 3000,
        baseLatencyMs: 100,
        latencyStdDevMs: 30,
        failureRate: 0.0005,
        maxConcurrentRequests: 500,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'node_cdn',
      type: ArchNodeType.CDN,
      position: { x: 650, y: 300 },
      data: {
        label: 'CloudFlare CDN',
        nodeType: ArchNodeType.CDN,
        cacheHitRate: 0.92,
        regions: ['US', 'EU', 'APAC', 'India'],
        maxRPS: 100000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.00001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    {
      id: 'edge_frontend_api_gateway',
      source: 'node_frontend',
      target: 'node_api_gateway',
      data: {
        protocol: 'http',
        bandwidthMbps: 1000,
        latencyOverheadMs: 5,
        encrypted: true,
      },
    },
    {
      id: 'edge_api_gateway_lb',
      source: 'node_api_gateway',
      target: 'node_load_balancer',
      data: {
        protocol: 'http',
        bandwidthMbps: 5000,
        latencyOverheadMs: 2,
        encrypted: false,
      },
    },
    {
      id: 'edge_lb_user_service',
      source: 'node_load_balancer',
      target: 'node_service_api',
      data: {
        protocol: 'http',
        bandwidthMbps: 2000,
        latencyOverheadMs: 1,
        encrypted: false,
      },
    },
    {
      id: 'edge_lb_order_service',
      source: 'node_load_balancer',
      target: 'node_service_order',
      data: {
        protocol: 'http',
        bandwidthMbps: 3000,
        latencyOverheadMs: 1,
        encrypted: false,
      },
    },
    {
      id: 'edge_lb_payment_service',
      source: 'node_load_balancer',
      target: 'node_service_payment',
      data: {
        protocol: 'http',
        bandwidthMbps: 1000,
        latencyOverheadMs: 2,
        encrypted: true,
      },
    },
    {
      id: 'edge_order_queue',
      source: 'node_service_order',
      target: 'node_queue',
      data: {
        protocol: 'kafka',
        bandwidthMbps: 1500,
        latencyOverheadMs: 5,
        encrypted: false,
      },
    },
    {
      id: 'edge_user_service_cache',
      source: 'node_service_api',
      target: 'node_cache',
      data: {
        protocol: 'tcp',
        bandwidthMbps: 500,
        latencyOverheadMs: 1,
        encrypted: false,
      },
    },
    {
      id: 'edge_order_service_cache',
      source: 'node_service_order',
      target: 'node_cache',
      data: {
        protocol: 'tcp',
        bandwidthMbps: 800,
        latencyOverheadMs: 1,
        encrypted: false,
      },
    },
    {
      id: 'edge_user_service_db',
      source: 'node_service_api',
      target: 'node_database',
      data: {
        protocol: 'tcp',
        bandwidthMbps: 2000,
        latencyOverheadMs: 2,
        encrypted: true,
      },
    },
    {
      id: 'edge_order_service_db',
      source: 'node_service_order',
      target: 'node_database',
      data: {
        protocol: 'tcp',
        bandwidthMbps: 3000,
        latencyOverheadMs: 2,
        encrypted: true,
      },
    },
    {
      id: 'edge_payment_service_db',
      source: 'node_service_payment',
      target: 'node_database',
      data: {
        protocol: 'tcp',
        bandwidthMbps: 500,
        latencyOverheadMs: 2,
        encrypted: true,
      },
    },
    {
      id: 'edge_frontend_cdn',
      source: 'node_frontend',
      target: 'node_cdn',
      data: {
        protocol: 'http',
        bandwidthMbps: 5000,
        latencyOverheadMs: 3,
        encrypted: true,
      },
    },
  ];

  return {
    id: 'ecommerce_arch',
    name: 'Sample E-Commerce Architecture',
    description: 'Complete e-commerce platform with all necessary components',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}
