import { ArchNodeType, type ArchNodeData, type Architecture, type ArchNode, type ArchEdge } from '@system-vis/shared';


/**
 * Discord-like Chat Application Architecture
 * Real-time messaging, WebSocket connections, user presence, message history
 */
export function getDiscordArchitecture(): Architecture {
  const nodes: ArchNode[] = [
    // Frontend
    {
      id: 'discord_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'Web/Desktop Client',
        nodeType: ArchNodeType.FRONTEND,
        instances: 3,
        cpuPerInstance: 2,
        memoryPerInstanceMB: 1024,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 10000,
        baseLatencyMs: 20,
        latencyStdDevMs: 5,
        failureRate: 0.001,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // API Gateway
    {
      id: 'discord_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 120 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 20000,
        authEnabled: true,
        corsEnabled: true,
        maxRPS: 20000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.0005,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // Load Balancer
    {
      id: 'discord_lb',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 240 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'least_connections',
        healthCheckIntervalMs: 5000,
        maxRPS: 15000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // WebSocket Server (Real-time messaging)
    {
      id: 'discord_websocket',
      type: ArchNodeType.WEBSOCKET_SERVER,
      position: { x: 50, y: 400 },
      data: {
        label: 'WebSocket Server',
        nodeType: ArchNodeType.WEBSOCKET_SERVER,
        instances: 8,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 50000,
        baseLatencyMs: 10,
        latencyStdDevMs: 3,
        failureRate: 0.001,
        maxConcurrentRequests: 500000,
        maxConnections: 100000,
        healthStatus: 'healthy',
      },
    },
    // Message Service
    {
      id: 'discord_message_svc',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 200, y: 400 },
      data: {
        label: 'Message Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 6,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 10000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 20000,
        healthStatus: 'healthy',
      },
    },
    // User Service
    {
      id: 'discord_user_svc',
      type: ArchNodeType.AUTH_SERVICE,
      position: { x: 350, y: 400 },
      data: {
        label: 'User/Auth Service',
        nodeType: ArchNodeType.AUTH_SERVICE,
        instances: 4,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 75,
        maxRPS: 5000,
        baseLatencyMs: 40,
        latencyStdDevMs: 15,
        failureRate: 0.01,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    // Search Engine (Message search)
    {
      id: 'discord_search',
      type: ArchNodeType.SEARCH_ENGINE,
      position: { x: 500, y: 400 },
      data: {
        label: 'Search Engine',
        nodeType: ArchNodeType.SEARCH_ENGINE,
        engineType: 'elasticsearch',
        maxMemoryMB: 16384,
        shardCount: 10,
        replicaCount: 2,
        indexingLatencyMs: 200,
        maxRPS: 3000,
        baseLatencyMs: 100,
        latencyStdDevMs: 30,
        failureRate: 0.005,
        maxConcurrentRequests: 5000,
        healthStatus: 'healthy',
      },
    },
    // Stream Processor (Activity streams, notifications)
    {
      id: 'discord_stream',
      type: ArchNodeType.STREAM_PROCESSOR,
      position: { x: 650, y: 400 },
      data: {
        label: 'Stream Processor',
        nodeType: ArchNodeType.STREAM_PROCESSOR,
        processorType: 'kafka-streams',
        instances: 5,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 80,
        processLatencyMs: 200,
        maxRPS: 20000,
        baseLatencyMs: 100,
        latencyStdDevMs: 50,
        failureRate: 0.003,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    // Primary Database
    {
      id: 'discord_db_primary',
      type: ArchNodeType.DATABASE,
      position: { x: 150, y: 600 },
      data: {
        label: 'PostgreSQL (Primary)',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 500,
        readReplicas: 3,
        avgQueryLatencyMs: 50,
        connectionPoolSize: 100,
        maxRPS: 5000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 500,
        healthStatus: 'healthy',
      },
    },
    // Message Cache (Redis)
    {
      id: 'discord_cache',
      type: ArchNodeType.CACHE,
      position: { x: 300, y: 600 },
      data: {
        label: 'Redis Cache',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 8192,
        hitRate: 0.9,
        ttlSeconds: 3600,
        evictionPolicy: 'lru',
        maxRPS: 100000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // Real-time DB (User presence, typing indicators)
    {
      id: 'discord_rtdb',
      type: ArchNodeType.REAL_TIME_DB,
      position: { x: 450, y: 600 },
      data: {
        label: 'Real-time DB',
        nodeType: ArchNodeType.REAL_TIME_DB,
        dbType: 'firebase',
        maxMemoryMB: 4096,
        maxConnections: 100000,
        replicationLatencyMs: 50,
        maxRPS: 50000,
        baseLatencyMs: 20,
        latencyStdDevMs: 10,
        failureRate: 0.002,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // Message Queue
    {
      id: 'discord_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 600, y: 600 },
      data: {
        label: 'Kafka Queue',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 500000,
        consumerCount: 10,
        consumerProcessingMs: 100,
        partitions: 20,
        maxRPS: 50000,
        baseLatencyMs: 10,
        latencyStdDevMs: 5,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // Notification Service
    {
      id: 'discord_notif',
      type: ArchNodeType.NOTIFICATION_SERVICE,
      position: { x: 750, y: 600 },
      data: {
        label: 'Notification Service',
        nodeType: ArchNodeType.NOTIFICATION_SERVICE,
        instances: 4,
        cpuPerInstance: 2,
        memoryPerInstanceMB: 1024,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 20000,
        baseLatencyMs: 30,
        latencyStdDevMs: 15,
        failureRate: 0.01,
        maxConcurrentRequests: 10000,
        channels: ['push', 'email', 'webhook'],
        healthStatus: 'healthy',
      },
    },
    // CDN
    {
      id: 'discord_cdn',
      type: ArchNodeType.CDN,
      position: { x: 600, y: 100 },
      data: {
        label: 'CDN',
        nodeType: ArchNodeType.CDN,
        cacheHitRate: 0.95,
        regions: ['US', 'EU', 'APAC', 'India'],
        maxRPS: 100000,
        baseLatencyMs: 10,
        latencyStdDevMs: 5,
        failureRate: 0.00001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    // Rest of connections...
    { id: 'e_frontend_gateway', source: 'discord_frontend', target: 'discord_gateway', data: { protocol: 'http', bandwidthMbps: 1000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e_gateway_lb', source: 'discord_gateway', target: 'discord_lb', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e_lb_ws', source: 'discord_lb', target: 'discord_websocket', data: { protocol: 'websocket', bandwidthMbps: 10000, latencyOverheadMs: 1, encrypted: true } },
    { id: 'e_lb_msg', source: 'discord_lb', target: 'discord_message_svc', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e_lb_user', source: 'discord_lb', target: 'discord_user_svc', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e_msg_search', source: 'discord_message_svc', target: 'discord_search', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e_msg_stream', source: 'discord_message_svc', target: 'discord_stream', data: { protocol: 'kafka', bandwidthMbps: 3000, latencyOverheadMs: 10, encrypted: false } },
    { id: 'e_msg_db', source: 'discord_message_svc', target: 'discord_db_primary', data: { protocol: 'tcp', bandwidthMbps: 3000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e_msg_cache', source: 'discord_message_svc', target: 'discord_cache', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e_user_db', source: 'discord_user_svc', target: 'discord_db_primary', data: { protocol: 'tcp', bandwidthMbps: 1000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e_user_rtdb', source: 'discord_user_svc', target: 'discord_rtdb', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e_stream_queue', source: 'discord_stream', target: 'discord_queue', data: { protocol: 'kafka', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e_queue_notif', source: 'discord_queue', target: 'discord_notif', data: { protocol: 'kafka', bandwidthMbps: 2000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e_frontend_cdn', source: 'discord_frontend', target: 'discord_cdn', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 3, encrypted: true } },
  ];

  return {
    id: 'discord_arch',
    name: 'Discord - Chat Application',
    description: 'Real-time messaging platform with WebSocket connections, message history search, and presence tracking',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

/**
 * Uber-like Ride Sharing Architecture
 * Real-time location tracking, matching algorithm, payments, notifications
 */
export function getUberArchitecture(): Architecture {
  const nodes: ArchNode[] = [
    {
      id: 'uber_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'Mobile App',
        nodeType: ArchNodeType.FRONTEND,
        instances: 5,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 50000,
        baseLatencyMs: 30,
        latencyStdDevMs: 10,
        failureRate: 0.005,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 120 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 50000,
        authEnabled: true,
        corsEnabled: true,
        maxRPS: 50000,
        baseLatencyMs: 20,
        latencyStdDevMs: 8,
        failureRate: 0.001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_lb',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 240 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'least_connections',
        healthCheckIntervalMs: 5000,
        maxRPS: 40000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_matching_svc',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 50, y: 400 },
      data: {
        label: 'Matching Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 10,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 8192,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 10000,
        baseLatencyMs: 500,
        latencyStdDevMs: 200,
        failureRate: 0.01,
        maxConcurrentRequests: 5000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_location_svc',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 200, y: 400 },
      data: {
        label: 'Location Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 8,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 100000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_payment_svc',
      type: ArchNodeType.PAYMENT_GATEWAY,
      position: { x: 350, y: 400 },
      data: {
        label: 'Payment Service',
        nodeType: ArchNodeType.PAYMENT_GATEWAY,
        provider: 'stripe',
        instances: 4,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        transactionLatencyMs: 500,
        maxRPS: 5000,
        baseLatencyMs: 500,
        latencyStdDevMs: 150,
        failureRate: 0.005,
        maxConcurrentRequests: 2000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_websocket',
      type: ArchNodeType.WEBSOCKET_SERVER,
      position: { x: 500, y: 400 },
      data: {
        label: 'WebSocket Server',
        nodeType: ArchNodeType.WEBSOCKET_SERVER,
        instances: 6,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 100000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.001,
        maxConcurrentRequests: 500000,
        maxConnections: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_stream',
      type: ArchNodeType.STREAM_PROCESSOR,
      position: { x: 650, y: 400 },
      data: {
        label: 'Stream Processor',
        nodeType: ArchNodeType.STREAM_PROCESSOR,
        processorType: 'kafka-streams',
        instances: 6,
        cpuPerInstance: 12,
        memoryPerInstanceMB: 8192,
        autoScale: true,
        autoScaleThreshold: 80,
        processLatencyMs: 300,
        maxRPS: 50000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.005,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_ml',
      type: ArchNodeType.ML_MODEL_SERVICE,
      position: { x: 800, y: 400 },
      data: {
        label: 'ML Service (Demand Prediction)',
        nodeType: ArchNodeType.ML_MODEL_SERVICE,
        instances: 3,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 16384,
        autoScale: true,
        autoScaleThreshold: 75,
        gpuSupport: true,
        inferenceLatencyMs: 200,
        maxRPS: 5000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.01,
        maxConcurrentRequests: 1000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_db',
      type: ArchNodeType.DATABASE,
      position: { x: 150, y: 600 },
      data: {
        label: 'PostgreSQL',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 1000,
        readReplicas: 4,
        avgQueryLatencyMs: 100,
        connectionPoolSize: 200,
        maxRPS: 10000,
        baseLatencyMs: 100,
        latencyStdDevMs: 50,
        failureRate: 0.01,
        maxConcurrentRequests: 1000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_timeseries',
      type: ArchNodeType.DATABASE,
      position: { x: 300, y: 600 },
      data: {
        label: 'TimescaleDB',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 500,
        readReplicas: 2,
        avgQueryLatencyMs: 50,
        connectionPoolSize: 100,
        maxRPS: 50000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 500,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_cache',
      type: ArchNodeType.CACHE,
      position: { x: 450, y: 600 },
      data: {
        label: 'Redis',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 16384,
        hitRate: 0.92,
        ttlSeconds: 600,
        evictionPolicy: 'lru',
        maxRPS: 500000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 600, y: 600 },
      data: {
        label: 'Kafka',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 1000000,
        consumerCount: 15,
        consumerProcessingMs: 200,
        partitions: 30,
        maxRPS: 100000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_notif',
      type: ArchNodeType.NOTIFICATION_SERVICE,
      position: { x: 750, y: 600 },
      data: {
        label: 'Notification Service',
        nodeType: ArchNodeType.NOTIFICATION_SERVICE,
        instances: 6,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 50000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.01,
        maxConcurrentRequests: 20000,
        channels: ['push', 'sms', 'email'],
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_analytics',
      type: ArchNodeType.ANALYTICS_SERVICE,
      position: { x: 900, y: 600 },
      data: {
        label: 'Analytics',
        nodeType: ArchNodeType.ANALYTICS_SERVICE,
        instances: 3,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 8192,
        autoScale: false,
        autoScaleThreshold: 85,
        maxRPS: 10000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.01,
        maxConcurrentRequests: 5000,
        dataWarehouse: 'bigquery',
        aggregationLatencyMs: 1000,
        healthStatus: 'healthy',
      },
    },
    {
      id: 'uber_cdn',
      type: ArchNodeType.CDN,
      position: { x: 600, y: 100 },
      data: {
        label: 'CDN',
        nodeType: ArchNodeType.CDN,
        cacheHitRate: 0.95,
        regions: ['US', 'EU', 'APAC', 'India', 'Brazil', 'MiddleEast'],
        maxRPS: 500000,
        baseLatencyMs: 20,
        latencyStdDevMs: 10,
        failureRate: 0.00001,
        maxConcurrentRequests: 1000000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    { id: 'e1', source: 'uber_frontend', target: 'uber_gateway', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e2', source: 'uber_gateway', target: 'uber_lb', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e3', source: 'uber_lb', target: 'uber_matching_svc', data: { protocol: 'grpc', bandwidthMbps: 5000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e4', source: 'uber_lb', target: 'uber_location_svc', data: { protocol: 'grpc', bandwidthMbps: 10000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e5', source: 'uber_lb', target: 'uber_payment_svc', data: { protocol: 'http', bandwidthMbps: 1000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e6', source: 'uber_lb', target: 'uber_websocket', data: { protocol: 'websocket', bandwidthMbps: 5000, latencyOverheadMs: 3, encrypted: true } },
    { id: 'e7', source: 'uber_matching_svc', target: 'uber_ml', data: { protocol: 'grpc', bandwidthMbps: 2000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e8', source: 'uber_location_svc', target: 'uber_timeseries', data: { protocol: 'tcp', bandwidthMbps: 5000, latencyOverheadMs: 3, encrypted: true } },
    { id: 'e9', source: 'uber_matching_svc', target: 'uber_cache', data: { protocol: 'tcp', bandwidthMbps: 3000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e10', source: 'uber_location_svc', target: 'uber_stream', data: { protocol: 'kafka', bandwidthMbps: 10000, latencyOverheadMs: 10, encrypted: false } },
    { id: 'e11', source: 'uber_stream', target: 'uber_queue', data: { protocol: 'kafka', bandwidthMbps: 10000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e12', source: 'uber_queue', target: 'uber_notif', data: { protocol: 'kafka', bandwidthMbps: 3000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e13', source: 'uber_queue', target: 'uber_analytics', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e14', source: 'uber_frontend', target: 'uber_cdn', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 5, encrypted: true } },
  ];

  return {
    id: 'uber_arch',
    name: 'Uber - Ride Sharing Platform',
    description: 'Real-time ride matching, location tracking, payment processing, ML-based demand prediction',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

/**
 * Netflix-like Video Streaming Architecture
 * Focus: Content delivery, adaptive bitrate streaming, recommendations, search
 */
export function getNetflixArchitecture(): Architecture {
  const nodes: ArchNode[] = [
    // Frontend
    {
      id: 'netflix_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'Web/Smart TV/Mobile',
        nodeType: ArchNodeType.FRONTEND,
        instances: 4,
        cpuPerInstance: 2,
        memoryPerInstanceMB: 1024,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 30000,
        baseLatencyMs: 25,
        latencyStdDevMs: 8,
        failureRate: 0.001,
        maxConcurrentRequests: 200000,
        healthStatus: 'healthy',
      },
    },
    // API Gateway
    {
      id: 'netflix_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 120 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 50000,
        authEnabled: true,
        corsEnabled: true,
        maxRPS: 50000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.0005,
        maxConcurrentRequests: 200000,
        healthStatus: 'healthy',
      },
    },
    // Load Balancer
    {
      id: 'netflix_lb',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 240 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'least_connections',
        healthCheckIntervalMs: 3000,
        maxRPS: 40000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 200000,
        healthStatus: 'healthy',
      },
    },
    // Search/Browse Service
    {
      id: 'netflix_search',
      type: ArchNodeType.SEARCH_ENGINE,
      position: { x: 50, y: 400 },
      data: {
        label: 'Search Engine',
        nodeType: ArchNodeType.SEARCH_ENGINE,
        engineType: 'opensearch',
        maxMemoryMB: 32768,
        shardCount: 20,
        replicaCount: 3,
        indexingLatencyMs: 500,
        maxRPS: 10000,
        baseLatencyMs: 80,
        latencyStdDevMs: 30,
        failureRate: 0.002,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    // Recommendation Engine (ML)
    {
      id: 'netflix_recommendation',
      type: ArchNodeType.ML_MODEL_SERVICE,
      position: { x: 200, y: 400 },
      data: {
        label: 'Recommendation Engine',
        nodeType: ArchNodeType.ML_MODEL_SERVICE,
        instances: 8,
        cpuPerInstance: 32,
        memoryPerInstanceMB: 32768,
        autoScale: true,
        autoScaleThreshold: 70,
        gpuSupport: true,
        inferenceLatencyMs: 300,
        maxRPS: 20000,
        baseLatencyMs: 300,
        latencyStdDevMs: 150,
        failureRate: 0.005,
        maxConcurrentRequests: 5000,
        healthStatus: 'healthy',
      },
    },
    // Streaming Service
    {
      id: 'netflix_streaming',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 350, y: 400 },
      data: {
        label: 'Streaming Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 12,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 8192,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 50000,
        baseLatencyMs: 40,
        latencyStdDevMs: 15,
        failureRate: 0.002,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // Video Processing (Transcoding)
    {
      id: 'netflix_encoding',
      type: ArchNodeType.STREAM_PROCESSOR,
      position: { x: 500, y: 400 },
      data: {
        label: 'Video Processor',
        nodeType: ArchNodeType.STREAM_PROCESSOR,
        processorType: 'spark',
        instances: 20,
        cpuPerInstance: 32,
        memoryPerInstanceMB: 32768,
        autoScale: true,
        autoScaleThreshold: 80,
        processLatencyMs: 5000,
        maxRPS: 1000,
        baseLatencyMs: 5000,
        latencyStdDevMs: 2000,
        failureRate: 0.01,
        maxConcurrentRequests: 500,
        healthStatus: 'healthy',
      },
    },
    // User Service
    {
      id: 'netflix_user_svc',
      type: ArchNodeType.AUTH_SERVICE,
      position: { x: 650, y: 400 },
      data: {
        label: 'User/Auth Service',
        nodeType: ArchNodeType.AUTH_SERVICE,
        instances: 5,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 75,
        maxRPS: 10000,
        baseLatencyMs: 30,
        latencyStdDevMs: 10,
        failureRate: 0.005,
        maxConcurrentRequests: 20000,
        healthStatus: 'healthy',
      },
    },
    // Content Metadata DB
    {
      id: 'netflix_db_content',
      type: ArchNodeType.DATABASE,
      position: { x: 100, y: 600 },
      data: {
        label: 'PostgreSQL (Content)',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 1000,
        readReplicas: 5,
        avgQueryLatencyMs: 50,
        connectionPoolSize: 200,
        maxRPS: 10000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 1000,
        healthStatus: 'healthy',
      },
    },
    // User Data Cache
    {
      id: 'netflix_cache',
      type: ArchNodeType.CACHE,
      position: { x: 250, y: 600 },
      data: {
        label: 'Redis Cache',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 65536,
        hitRate: 0.95,
        ttlSeconds: 1800,
        evictionPolicy: 'lru',
        maxRPS: 500000,
        baseLatencyMs: 3,
        latencyStdDevMs: 1,
        failureRate: 0.0001,
        maxConcurrentRequests: 200000,
        healthStatus: 'healthy',
      },
    },
    // Real-time Tracking (View history, watch lists)
    {
      id: 'netflix_rtdb',
      type: ArchNodeType.REAL_TIME_DB,
      position: { x: 400, y: 600 },
      data: {
        label: 'Real-time DB',
        nodeType: ArchNodeType.REAL_TIME_DB,
        dbType: 'firebase',
        maxMemoryMB: 16384,
        maxConnections: 500000,
        replicationLatencyMs: 100,
        maxRPS: 100000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.002,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
    // Event Stream (User events, view history)
    {
      id: 'netflix_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 550, y: 600 },
      data: {
        label: 'Kafka',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 5000000,
        consumerCount: 20,
        consumerProcessingMs: 500,
        partitions: 50,
        maxRPS: 200000,
        baseLatencyMs: 20,
        latencyStdDevMs: 10,
        failureRate: 0.0001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
    // Analytics Engine
    {
      id: 'netflix_analytics',
      type: ArchNodeType.ANALYTICS_SERVICE,
      position: { x: 700, y: 600 },
      data: {
        label: 'Analytics',
        nodeType: ArchNodeType.ANALYTICS_SERVICE,
        instances: 5,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 16384,
        autoScale: false,
        autoScaleThreshold: 85,
        maxRPS: 100000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.005,
        maxConcurrentRequests: 10000,
        dataWarehouse: 'bigquery',
        aggregationLatencyMs: 2000,
        healthStatus: 'healthy',
      },
    },
    // Global CDN
    {
      id: 'netflix_cdn',
      type: ArchNodeType.CDN,
      position: { x: 600, y: 100 },
      data: {
        label: 'Global CDN',
        nodeType: ArchNodeType.CDN,
        cacheHitRate: 0.98,
        regions: ['US-East', 'US-West', 'EU', 'APAC', 'India', 'Brazil', 'Japan', 'Australia'],
        maxRPS: 1000000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.00001,
        maxConcurrentRequests: 5000000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    { id: 'e1', source: 'netflix_frontend', target: 'netflix_gateway', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e2', source: 'netflix_gateway', target: 'netflix_lb', data: { protocol: 'http', bandwidthMbps: 20000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e3', source: 'netflix_lb', target: 'netflix_search', data: { protocol: 'http', bandwidthMbps: 3000, latencyOverheadMs: 3, encrypted: false } },
    { id: 'e4', source: 'netflix_lb', target: 'netflix_recommendation', data: { protocol: 'grpc', bandwidthMbps: 10000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e5', source: 'netflix_lb', target: 'netflix_streaming', data: { protocol: 'http', bandwidthMbps: 50000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e6', source: 'netflix_streaming', target: 'netflix_rtdb', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e7', source: 'netflix_recommendation', target: 'netflix_cache', data: { protocol: 'tcp', bandwidthMbps: 5000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e8', source: 'netflix_search', target: 'netflix_db_content', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 3, encrypted: false } },
    { id: 'e9', source: 'netflix_streaming', target: 'netflix_queue', data: { protocol: 'kafka', bandwidthMbps: 20000, latencyOverheadMs: 10, encrypted: false } },
    { id: 'e10', source: 'netflix_queue', target: 'netflix_analytics', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e11', source: 'netflix_frontend', target: 'netflix_cdn', data: { protocol: 'http', bandwidthMbps: 50000, latencyOverheadMs: 3, encrypted: true } },
  ];

  return {
    id: 'netflix_arch',
    name: 'Netflix - Video Streaming Platform',
    description: 'Adaptive bitrate streaming with ML recommendations, global CDN, content processing, analytics',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

/**
 * Amazon-like E-commerce Architecture
 * Focus: Product catalog, shopping cart, orders, payment, inventory, recommendations
 */
export function getAmazonArchitecture(): Architecture {
  const nodes: ArchNode[] = [
    // Frontend
    {
      id: 'amazon_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'Web/Mobile Client',
        nodeType: ArchNodeType.FRONTEND,
        instances: 6,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 100000,
        baseLatencyMs: 30,
        latencyStdDevMs: 10,
        failureRate: 0.001,
        maxConcurrentRequests: 300000,
        healthStatus: 'healthy',
      },
    },
    // API Gateway
    {
      id: 'amazon_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 120 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 100000,
        authEnabled: true,
        corsEnabled: true,
        maxRPS: 100000,
        baseLatencyMs: 15,
        latencyStdDevMs: 5,
        failureRate: 0.0005,
        maxConcurrentRequests: 300000,
        healthStatus: 'healthy',
      },
    },
    // Load Balancer
    {
      id: 'amazon_lb',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 240 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'least_connections',
        healthCheckIntervalMs: 3000,
        maxRPS: 80000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 300000,
        healthStatus: 'healthy',
      },
    },
    // Product Search Service
    {
      id: 'amazon_product_search',
      type: ArchNodeType.SEARCH_ENGINE,
      position: { x: 50, y: 400 },
      data: {
        label: 'Product Search',
        nodeType: ArchNodeType.SEARCH_ENGINE,
        engineType: 'opensearch',
        maxMemoryMB: 65536,
        shardCount: 50,
        replicaCount: 4,
        indexingLatencyMs: 300,
        maxRPS: 50000,
        baseLatencyMs: 100,
        latencyStdDevMs: 40,
        failureRate: 0.001,
        maxConcurrentRequests: 20000,
        healthStatus: 'healthy',
      },
    },
    // Product Service
    {
      id: 'amazon_product_svc',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 200, y: 400 },
      data: {
        label: 'Product Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 8,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 30000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 30000,
        healthStatus: 'healthy',
      },
    },
    // Cart Service
    {
      id: 'amazon_cart_svc',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 350, y: 400 },
      data: {
        label: 'Cart Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 6,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 50000,
        baseLatencyMs: 30,
        latencyStdDevMs: 10,
        failureRate: 0.002,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // Order Service
    {
      id: 'amazon_order_svc',
      type: ArchNodeType.ORDER_SERVICE,
      position: { x: 500, y: 400 },
      data: {
        label: 'Order Service',
        nodeType: ArchNodeType.ORDER_SERVICE,
        instances: 8,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 20000,
        baseLatencyMs: 100,
        latencyStdDevMs: 40,
        failureRate: 0.01,
        maxConcurrentRequests: 15000,
        healthStatus: 'healthy',
      },
    },
    // Payment Gateway
    {
      id: 'amazon_payment',
      type: ArchNodeType.PAYMENT_GATEWAY,
      position: { x: 650, y: 400 },
      data: {
        label: 'Payment Gateway',
        nodeType: ArchNodeType.PAYMENT_GATEWAY,
        provider: 'stripe',
        instances: 6,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        transactionLatencyMs: 800,
        maxRPS: 10000,
        baseLatencyMs: 800,
        latencyStdDevMs: 300,
        failureRate: 0.01,
        maxConcurrentRequests: 5000,
        healthStatus: 'healthy',
      },
    },
    // Recommendation Engine (ML)
    {
      id: 'amazon_recommendation',
      type: ArchNodeType.ML_MODEL_SERVICE,
      position: { x: 800, y: 400 },
      data: {
        label: 'Recommendation Engine',
        nodeType: ArchNodeType.ML_MODEL_SERVICE,
        instances: 6,
        cpuPerInstance: 32,
        memoryPerInstanceMB: 32768,
        autoScale: true,
        autoScaleThreshold: 70,
        gpuSupport: true,
        inferenceLatencyMs: 200,
        maxRPS: 10000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.005,
        maxConcurrentRequests: 5000,
        healthStatus: 'healthy',
      },
    },
    // Product Catalog DB
    {
      id: 'amazon_db_products',
      type: ArchNodeType.DATABASE,
      position: { x: 100, y: 600 },
      data: {
        label: 'PostgreSQL (Products)',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'dynamodb',
        maxConnections: 2000,
        readReplicas: 6,
        avgQueryLatencyMs: 50,
        connectionPoolSize: 300,
        maxRPS: 50000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.005,
        maxConcurrentRequests: 2000,
        healthStatus: 'healthy',
      },
    },
    // Order DB
    {
      id: 'amazon_db_orders',
      type: ArchNodeType.DATABASE,
      position: { x: 250, y: 600 },
      data: {
        label: 'PostgreSQL (Orders)',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 1000,
        readReplicas: 4,
        avgQueryLatencyMs: 100,
        connectionPoolSize: 200,
        maxRPS: 10000,
        baseLatencyMs: 100,
        latencyStdDevMs: 50,
        failureRate: 0.01,
        maxConcurrentRequests: 1000,
        healthStatus: 'healthy',
      },
    },
    // Cache (Product, Cart)
    {
      id: 'amazon_cache',
      type: ArchNodeType.CACHE,
      position: { x: 400, y: 600 },
      data: {
        label: 'Redis Cache',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 131072,
        hitRate: 0.93,
        ttlSeconds: 3600,
        evictionPolicy: 'lru',
        maxRPS: 500000,
        baseLatencyMs: 5,
        latencyStdDevMs: 2,
        failureRate: 0.0001,
        maxConcurrentRequests: 300000,
        healthStatus: 'healthy',
      },
    },
    // Event Stream (Order events, page views, purchases)
    {
      id: 'amazon_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 550, y: 600 },
      data: {
        label: 'Kafka',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 10000000,
        consumerCount: 30,
        consumerProcessingMs: 300,
        partitions: 100,
        maxRPS: 200000,
        baseLatencyMs: 15,
        latencyStdDevMs: 8,
        failureRate: 0.0001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
    // Analytics/Data Warehouse
    {
      id: 'amazon_analytics',
      type: ArchNodeType.ANALYTICS_SERVICE,
      position: { x: 700, y: 600 },
      data: {
        label: 'Analytics',
        nodeType: ArchNodeType.ANALYTICS_SERVICE,
        instances: 8,
        cpuPerInstance: 32,
        memoryPerInstanceMB: 32768,
        autoScale: false,
        autoScaleThreshold: 85,
        maxRPS: 100000,
        baseLatencyMs: 300,
        latencyStdDevMs: 150,
        failureRate: 0.005,
        maxConcurrentRequests: 10000,
        dataWarehouse: 'redshift',
        aggregationLatencyMs: 3000,
        healthStatus: 'healthy',
      },
    },
    // Notification Service
    {
      id: 'amazon_notif',
      type: ArchNodeType.NOTIFICATION_SERVICE,
      position: { x: 850, y: 600 },
      data: {
        label: 'Notification Service',
        nodeType: ArchNodeType.NOTIFICATION_SERVICE,
        instances: 6,
        cpuPerInstance: 4,
        memoryPerInstanceMB: 2048,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 50000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.01,
        maxConcurrentRequests: 20000,
        channels: ['email', 'sms', 'push'],
        healthStatus: 'healthy',
      },
    },
    // CDN
    {
      id: 'amazon_cdn',
      type: ArchNodeType.CDN,
      position: { x: 600, y: 100 },
      data: {
        label: 'Global CDN',
        nodeType: ArchNodeType.CDN,
        cacheHitRate: 0.96,
        regions: ['US-East', 'US-West', 'EU-West', 'EU-Central', 'APAC', 'India'],
        maxRPS: 500000,
        baseLatencyMs: 20,
        latencyStdDevMs: 8,
        failureRate: 0.00001,
        maxConcurrentRequests: 2000000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    { id: 'e1', source: 'amazon_frontend', target: 'amazon_gateway', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e2', source: 'amazon_gateway', target: 'amazon_lb', data: { protocol: 'http', bandwidthMbps: 20000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e3', source: 'amazon_lb', target: 'amazon_product_search', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 3, encrypted: false } },
    { id: 'e4', source: 'amazon_lb', target: 'amazon_product_svc', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e5', source: 'amazon_product_svc', target: 'amazon_cache', data: { protocol: 'tcp', bandwidthMbps: 5000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e6', source: 'amazon_product_svc', target: 'amazon_db_products', data: { protocol: 'tcp', bandwidthMbps: 3000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e7', source: 'amazon_lb', target: 'amazon_cart_svc', data: { protocol: 'http', bandwidthMbps: 3000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e8', source: 'amazon_cart_svc', target: 'amazon_cache', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e9', source: 'amazon_lb', target: 'amazon_order_svc', data: { protocol: 'http', bandwidthMbps: 2000, latencyOverheadMs: 2, encrypted: false } },
    { id: 'e10', source: 'amazon_order_svc', target: 'amazon_db_orders', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 3, encrypted: true } },
    { id: 'e11', source: 'amazon_order_svc', target: 'amazon_payment', data: { protocol: 'http', bandwidthMbps: 1000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e12', source: 'amazon_order_svc', target: 'amazon_queue', data: { protocol: 'kafka', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e13', source: 'amazon_product_svc', target: 'amazon_recommendation', data: { protocol: 'grpc', bandwidthMbps: 8000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e14', source: 'amazon_queue', target: 'amazon_analytics', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 10, encrypted: true } },
    { id: 'e15', source: 'amazon_queue', target: 'amazon_notif', data: { protocol: 'kafka', bandwidthMbps: 3000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e16', source: 'amazon_frontend', target: 'amazon_cdn', data: { protocol: 'http', bandwidthMbps: 20000, latencyOverheadMs: 3, encrypted: true } },
  ];

  return {
    id: 'amazon_arch',
    name: 'Amazon - E-commerce Platform',
    description: 'Product catalog search, shopping cart, order processing, payment integration, personalized recommendations',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

/**
 * Stripe-like Payment Platform Architecture
 * Focus: Payment processing, fraud detection, webhook delivery, transaction settlement, PCI compliance
 */
export function getStripeArchitecture(): Architecture {
  const nodes: ArchNode[] = [
    // Frontend/API Endpoint
    {
      id: 'stripe_frontend',
      type: ArchNodeType.FRONTEND,
      position: { x: 400, y: 0 },
      data: {
        label: 'API Clients',
        nodeType: ArchNodeType.FRONTEND,
        instances: 8,
        cpuPerInstance: 2,
        memoryPerInstanceMB: 1024,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 50000,
        baseLatencyMs: 10,
        latencyStdDevMs: 3,
        failureRate: 0.0001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // API Gateway (PCI Compliant)
    {
      id: 'stripe_gateway',
      type: ArchNodeType.API_GATEWAY,
      position: { x: 400, y: 120 },
      data: {
        label: 'API Gateway',
        nodeType: ArchNodeType.API_GATEWAY,
        rateLimitRPS: 100000,
        authEnabled: true,
        corsEnabled: false,
        maxRPS: 100000,
        baseLatencyMs: 10,
        latencyStdDevMs: 3,
        failureRate: 0.00001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // Load Balancer
    {
      id: 'stripe_lb',
      type: ArchNodeType.LOAD_BALANCER,
      position: { x: 200, y: 240 },
      data: {
        label: 'Load Balancer',
        nodeType: ArchNodeType.LOAD_BALANCER,
        algorithm: 'round_robin',
        healthCheckIntervalMs: 1000,
        maxRPS: 80000,
        baseLatencyMs: 3,
        latencyStdDevMs: 1,
        failureRate: 0.00001,
        maxConcurrentRequests: 100000,
        healthStatus: 'healthy',
      },
    },
    // Fraud Detection (ML)
    {
      id: 'stripe_fraud',
      type: ArchNodeType.ML_MODEL_SERVICE,
      position: { x: 50, y: 400 },
      data: {
        label: 'Fraud Detection',
        nodeType: ArchNodeType.ML_MODEL_SERVICE,
        instances: 8,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 16384,
        autoScale: true,
        autoScaleThreshold: 75,
        gpuSupport: true,
        inferenceLatencyMs: 150,
        maxRPS: 50000,
        baseLatencyMs: 150,
        latencyStdDevMs: 75,
        failureRate: 0.001,
        maxConcurrentRequests: 20000,
        healthStatus: 'healthy',
      },
    },
    // Payment Processing Service
    {
      id: 'stripe_payment_svc',
      type: ArchNodeType.PAYMENT_GATEWAY,
      position: { x: 200, y: 400 },
      data: {
        label: 'Payment Processor',
        nodeType: ArchNodeType.PAYMENT_GATEWAY,
        provider: 'stripe',
        instances: 12,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 8192,
        transactionLatencyMs: 1000,
        maxRPS: 30000,
        baseLatencyMs: 1000,
        latencyStdDevMs: 400,
        failureRate: 0.005,
        maxConcurrentRequests: 10000,
        healthStatus: 'healthy',
      },
    },
    // Webhook Service
    {
      id: 'stripe_webhook',
      type: ArchNodeType.NOTIFICATION_SERVICE,
      position: { x: 350, y: 400 },
      data: {
        label: 'Webhook Delivery',
        nodeType: ArchNodeType.NOTIFICATION_SERVICE,
        instances: 10,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 85,
        maxRPS: 100000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.01,
        maxConcurrentRequests: 50000,
        channels: ['webhook'],
        healthStatus: 'healthy',
      },
    },
    // Idempotency/Deduplication Service
    {
      id: 'stripe_idempotency',
      type: ArchNodeType.CUSTOM_SERVICE,
      position: { x: 500, y: 400 },
      data: {
        label: 'Idempotency Service',
        nodeType: ArchNodeType.CUSTOM_SERVICE,
        instances: 6,
        cpuPerInstance: 8,
        memoryPerInstanceMB: 4096,
        autoScale: true,
        autoScaleThreshold: 80,
        maxRPS: 50000,
        baseLatencyMs: 20,
        latencyStdDevMs: 5,
        failureRate: 0.0001,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // Transaction Ledger
    {
      id: 'stripe_ledger',
      type: ArchNodeType.STREAM_PROCESSOR,
      position: { x: 650, y: 400 },
      data: {
        label: 'Transaction Ledger',
        nodeType: ArchNodeType.STREAM_PROCESSOR,
        processorType: 'kafka-streams',
        instances: 8,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 8192,
        autoScale: true,
        autoScaleThreshold: 80,
        processLatencyMs: 200,
        maxRPS: 100000,
        baseLatencyMs: 200,
        latencyStdDevMs: 100,
        failureRate: 0.001,
        maxConcurrentRequests: 50000,
        healthStatus: 'healthy',
      },
    },
    // Transaction DB (Primary)
    {
      id: 'stripe_db_primary',
      type: ArchNodeType.DATABASE,
      position: { x: 100, y: 600 },
      data: {
        label: 'PostgreSQL (Transactions)',
        nodeType: ArchNodeType.DATABASE,
        dbType: 'postgresql',
        maxConnections: 2000,
        readReplicas: 6,
        avgQueryLatencyMs: 50,
        connectionPoolSize: 400,
        maxRPS: 100000,
        baseLatencyMs: 50,
        latencyStdDevMs: 20,
        failureRate: 0.001,
        maxConcurrentRequests: 2000,
        healthStatus: 'healthy',
      },
    },
    // Cache (Idempotency keys, rate limiting)
    {
      id: 'stripe_cache',
      type: ArchNodeType.CACHE,
      position: { x: 250, y: 600 },
      data: {
        label: 'Redis Cache',
        nodeType: ArchNodeType.CACHE,
        cacheType: 'redis',
        maxMemoryMB: 65536,
        hitRate: 0.98,
        ttlSeconds: 86400,
        evictionPolicy: 'lru',
        maxRPS: 500000,
        baseLatencyMs: 2,
        latencyStdDevMs: 1,
        failureRate: 0.00001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
    // Event Stream (Payment events, refunds, disputes)
    {
      id: 'stripe_queue',
      type: ArchNodeType.QUEUE,
      position: { x: 400, y: 600 },
      data: {
        label: 'Kafka',
        nodeType: ArchNodeType.QUEUE,
        queueType: 'kafka',
        maxQueueDepth: 5000000,
        consumerCount: 20,
        consumerProcessingMs: 100,
        partitions: 100,
        maxRPS: 200000,
        baseLatencyMs: 10,
        latencyStdDevMs: 5,
        failureRate: 0.00001,
        maxConcurrentRequests: 500000,
        healthStatus: 'healthy',
      },
    },
    // Analytics & Reporting
    {
      id: 'stripe_analytics',
      type: ArchNodeType.ANALYTICS_SERVICE,
      position: { x: 550, y: 600 },
      data: {
        label: 'Analytics',
        nodeType: ArchNodeType.ANALYTICS_SERVICE,
        instances: 6,
        cpuPerInstance: 16,
        memoryPerInstanceMB: 16384,
        autoScale: false,
        autoScaleThreshold: 85,
        maxRPS: 50000,
        baseLatencyMs: 300,
        latencyStdDevMs: 150,
        failureRate: 0.005,
        maxConcurrentRequests: 5000,
        dataWarehouse: 'snowflake',
        aggregationLatencyMs: 2000,
        healthStatus: 'healthy',
      },
    },
  ];

  const edges: ArchEdge[] = [
    { id: 'e1', source: 'stripe_frontend', target: 'stripe_gateway', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e2', source: 'stripe_gateway', target: 'stripe_lb', data: { protocol: 'http', bandwidthMbps: 10000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e3', source: 'stripe_lb', target: 'stripe_fraud', data: { protocol: 'grpc', bandwidthMbps: 3000, latencyOverheadMs: 3, encrypted: true } },
    { id: 'e4', source: 'stripe_fraud', target: 'stripe_cache', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e5', source: 'stripe_lb', target: 'stripe_payment_svc', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e6', source: 'stripe_payment_svc', target: 'stripe_idempotency', data: { protocol: 'http', bandwidthMbps: 3000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e7', source: 'stripe_idempotency', target: 'stripe_cache', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 1, encrypted: false } },
    { id: 'e8', source: 'stripe_payment_svc', target: 'stripe_db_primary', data: { protocol: 'tcp', bandwidthMbps: 2000, latencyOverheadMs: 2, encrypted: true } },
    { id: 'e9', source: 'stripe_payment_svc', target: 'stripe_ledger', data: { protocol: 'kafka', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e10', source: 'stripe_payment_svc', target: 'stripe_webhook', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 5, encrypted: true } },
    { id: 'e11', source: 'stripe_ledger', target: 'stripe_queue', data: { protocol: 'kafka', bandwidthMbps: 10000, latencyOverheadMs: 5, encrypted: false } },
    { id: 'e12', source: 'stripe_queue', target: 'stripe_analytics', data: { protocol: 'http', bandwidthMbps: 5000, latencyOverheadMs: 10, encrypted: true } },
  ];

  return {
    id: 'stripe_arch',
    name: 'Stripe - Payment Platform',
    description: 'High-reliability payment processing with fraud detection, webhook delivery, transaction ledger, PCI compliant',
    nodes,
    edges,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

